service: awsboilerplate

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}

#  enviroment:
#    CONFIG:

  custom:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk

package:
  # Pack all functions individually with all necessary dependencies.
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  index:
    handler: functions/main/index.handler
    events:
      - http:
          path: /
          method: GET
